apiVersion: v1
kind: Service
metadata:
  name: my-httpd-svc
  labels:
    app: httpd
spec:
  type: LoadBalancer
  ports:
  - port: 8080
  selector:
    app: httpd
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-httpd
  labels:
    app: httpd
spec:
  replicas: 5
  selector:
    matchLabels:
      app: httpd
  template:
    metadata:
      labels:
        app: httpd
    spec:
      containers:
      - name: httpd
        image: httpd:latest
        ports:
        - containerPort: 8080
